feat: User api 마무리
Techeer-Hogwarts/nest pull request #20
Opened 2024-10-25 17:43 UTC by jungeunyooon

## 요약

<br><br>

## 작업 내용
프로필 사진 동기화, 닉네임 업데이트, 프로필 조회, 권한 관련 api 등 모든 유저 api 작업했습니다
<br><br>

## 참고 사항
실제 슬랙 이메일로 테스트해야합니다.
<br><br>

## 관련 이슈

SCRUM-137

2024-10-25 18:13 UTC, printSANO requested changes

2024-10-25 18:13 UTC, printSANO commented on prisma/migrations/20241019120802_init/migration.sql
> +    "updatedAt" TIMESTAMP(3) NOT NULL,
값 디폴트랑 업데이트때 값 바뀌는 어노테이션이 없습니다

2024-10-26 14:09 UTC, jungeunyooon commented on prisma/migrations/20241019120802_init/migration.sql
> +    "updatedAt" TIMESTAMP(3) NOT NULL,
지금 다시 만들려고 하는데, 다른 코드들이랑 충돌생겨서 최신사항 다 풀받고 다시 마이그레이션 파일 만들어야 할 것 같습니다 ㅠ 지금은 계속 오류나서 안되네여.....

2024-10-26 17:09 UTC, suhach0523 approved these changes
수고하셨습니다!!!

2024-10-26 17:33 UTC, dlwhsk0 reviewed
prisma에 일부 중복되는 게 있는 것 같아요
프리즈마에 문제가 있다고 했었는데 이거 때문은 아닌...가?

나중에 jwt 랑 쿠키 관련 내용 알려주세요 🙌🙇‍♀️

2024-10-26 17:33 UTC, dlwhsk0 commented on prisma/schema.prisma
> +model TeamMember {
model TeamMember가 2개인 것 같아요

2024-10-26 17:33 UTC, dlwhsk0 commented on prisma/schema.prisma
> +model Resume {
Resume도 2개?

2024-10-26 17:35 UTC, jungeunyooon commented on prisma/schema.prisma
> +model Resume {
마자요 이 파일 문제입니당 ㅜ

2024-10-26 17:42 UTC, dlwhsk0 commented on prisma/schema.prisma
>    id          Int       @id @default(autoincrement())
model TeamMember가 2개인 것 같아요

2024-10-27 05:44 UTC, merged