feat: 팀매칭 API 구현
Techeer-Hogwarts/nest pull request #23
Opened 2024-11-05 16:12 UTC by jihye1006

## 요약
팀매칭 API 구현
<br><br>

## 작업 내용

<br><br>

## 참고 사항

<br><br>

## 관련 이슈

-   Close #이슈번호

<br><br>

2024-11-09 04:17 UTC, dlwhsk0 commented on src/modules/teams/dto/request/create.team.request.ts
파일명이랑 클래스명이랑 일치가 안 이뤄져서 헷갈릴 수 있을 것 같아요

팀 공고를 생성할 때 공고를 생성하는 유저 아이디가 안 들어가는 것 같은데 공고를 생성한 멤버는 자동으로 팀 멤버에 들어가야 하지 않을까요?

2024-11-09 04:17 UTC, dlwhsk0 commented on src/modules/teamStacks/teamStack.controller.ts
빈 파일들은 나중에 추가될 코드가 있나요?

2024-11-09 04:29 UTC, jihye1006 commented on src/modules/stacks/entities/stack.entity.ts
> +export { Stack };
자꾸 다른 스택으로 인식해서 넣어둔 거긴한데 확인해보고 괜찮으면 빼도록 하겠습니다!

2024-11-09 04:29 UTC, jihye1006 commented on src/modules/teamMembers/domain/teamMember.entity.ts
넵

2024-11-09 04:30 UTC, jihye1006 commented on src/modules/teamMembers/domain/teamMember.entity.ts
> +    }
이것도 인식이 안 돼서 코드 수정중에 넣었었다가 다시 코드 바꾸면서 사용 안 하게 된 건데 수정하도록 하겠습니다!

2024-11-09 04:31 UTC, jihye1006 commented on src/modules/teams/dto/request/create.team.request.ts
그러면 announcement 말고 team으로 통일하겠습니다

넵 반영하겠습니다~

2024-11-09 04:32 UTC, jihye1006 commented on src/modules/teamStacks/teamStack.controller.ts
스택을 서버에서 다 정해두고 하면 필요 없을 거 같긴한데 아직 확실하게 그 부분에 대해서 말 안 한 거 같아서 일단 파일들만 생성해뒀습니다!

2024-11-09 04:33 UTC, printSANO requested changes

2024-11-09 04:33 UTC, printSANO commented on src/modules/teams/test/mock-data.ts
> +    team.teamStacks = [teamStack as TeamStackEntity];
https://sonarcloud.io/project/issues?pullRequest=23&open=AZL9Go7MazKBKOFUdGMg&id=Techeer-Hogwarts_nest

확인 바라겠습니다

2024-11-09 04:54 UTC, jihye1006 commented on src/modules/teams/test/mock-data.ts
> +    team.teamStacks = [teamStack as TeamStackEntity];
넵

2024-11-22 12:19 UTC, dlwhsk0 approved these changes

2024-11-22 12:19 UTC, merged