feat: 유저 도메인 반환값 처리 및 추가 Api 작업
Techeer-Hogwarts/nest pull request #35
Opened 2024-12-14 02:32 UTC by jungeunyooon

## 작업 내용
* http://localhost:8000/api/v1/users/profiles : API에 사용자가 참여한 스터디, 프로젝트 추가하고, 깃허브,블로그 주소 빼기
* http://localhost:8000/api/v1/users : API에 사용자가 참여만 프로젝트, 스터디 추가
* 토큰말고 UserID로 조회하는 api 필요함 반환값은 http://localhost:8000/api/v1/users 이거랑 동일
* 유저별 세션,블로그, 이력서 조회 반환값 필요한것만 반환하게 통일 
* CORS 
* 커스텀 예외처리

<br><br>

## 참고 사항
-  유저별 세션,블로그, 이력서 조회 반환값 더 필요한 필드 있으면 말해주세요! 추가하겠습니당
<br><br>

## 관련 이슈

-   SCRUM-169

<br><br>

2024-12-18 07:18 UTC, printSANO requested changes

2024-12-18 07:18 UTC, printSANO commented on src/main.ts
> +    const originAddress = [
여기에 버셀 주소도 추가 해야될수도 있어요

2024-12-18 07:18 UTC, printSANO commented on src/modules/resumes/repository/resume.repository.ts
> +        const resume: any = await this.prisma.resume.findUnique({
비번 같은거 리턴 안하려고 any타입 쓴거 같은데 커스텀 엔티티 하나 더 생성 하는건 어떤가요?

2024-12-18 07:18 UTC, printSANO commented on src/modules/sessions/repository/session.repository.ts
> +    ): Promise<any> {
여기도

2024-12-20 06:28 UTC, jungeunyooon commented on src/main.ts
> +    const originAddress = [
수정했습니당~

2024-12-20 06:29 UTC, jungeunyooon commented on src/modules/sessions/repository/session.repository.ts
> +    ): Promise<any> {
any로 해둔 부분 바꾸려면 유저 말고 다른 도메인도 많이 건들여야해서 사고칠까봐 약간 두려워요 다른 분들한테 부탁드리겠슴돠

2024-12-24 01:03 UTC, merged