feat: 테커인 블로그 크롤링 스케줄링 구현 및 예외 처리 구현
Techeer-Hogwarts/nest pull request #36
Opened 2024-12-16 18:09 UTC by dlwhsk0

## 요약

테커인 블로그 크롤링 스케줄링 구현 및 예외 처리 구현

<br><br>

## 작업 내용

- 테커인 블로그 크롤링 스케줄링 구현
  - 매일 새벽 3시 실행됨
- 예외 처리 구현

<br><br>

## 참고 사항

<br><br>

## 관련 이슈

-   issue: SCRUM-176

<br><br>

2024-12-16 18:33 UTC, printSANO requested changes
피드백 적었습니다

2024-12-16 18:33 UTC, printSANO commented on src/global/rabbitmq/rabbitmq.service.ts
> +        this.connection = amqp.connect(['amqp://guest:guest@localhost:5672']);
이거 변수로 빼주세요

2024-12-16 18:33 UTC, printSANO commented on src/global/redis/redis.service.ts
> +            url: 'redis://localhost:6379',
여기도 변수로 빼주세요

2024-12-16 18:33 UTC, printSANO commented on src/global/redis/redis.service.ts
> +            url: 'redis://localhost:6379',
비번 설정도 부탁해요

2024-12-16 18:33 UTC, printSANO commented on src/global/redis/redis.service.ts
> +        await this.client.del(taskId);
삭제가 안되면 어떻게 하나요? 예외처리?

2024-12-16 18:33 UTC, printSANO commented on src/modules/blogs/blog.service.ts
> +    async createBlog(crawlingBlogDto: CrawlingBlogResponse): Promise<void> {
회원가입 할때 처음에 등록할때는 무조건 어제 3개가 아닙니다.

2024-12-30 18:11 UTC, dlwhsk0 commented on src/global/redis/redis.service.ts
> +        await this.client.del(taskId);
redis의 expire 처리?

2024-12-31 07:40 UTC, jungeunyooon approved these changes

2024-12-31 07:42 UTC, jungeunyooon commented
고생하셨습니다~~

2024-12-31 08:16 UTC, suhach0523 approved these changes
수고하셨어여!!

2025-01-05 06:22 UTC, dlwhsk0 commented on src/global/redis/redis.service.ts
> +        await this.client.del(taskId);
deleteTask 처리 후, 안 된 것들은 TTL 10분 설정 (처리 안 됐으면 로그 남도록)

2025-01-05 06:33 UTC, dlwhsk0 commented on src/global/redis/redis.service.ts
> +        await this.client.del(taskId);
- [ ] 같은 블로그가 두 번 작성되는 일이 없게 url로 upsert 처리를 해둬야겠다

2025-01-05 15:06 UTC, merged